apiVersion: v1
kind: Service
metadata:
  name: http
  namespace: {{ .Values.projectName | quote }}
  labels:
    app: {{ .Values.projectName | quote }}
    env: {{ .Values.labels.env | quote }}
spec:
  selector:
    app: {{ .Values.projectName | quote }}
    pod: workspace
    env: {{ .Values.labels.env | quote }}
  type: NodePort
  sessionAffinity: ClientIP
  ports: 
    - name: http
      port: 80
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: {{ .Values.projectName | quote }}
  labels:
    app: {{ .Values.projectName | quote }}
    env: {{ .Values.labels.env | quote }}
spec:
  selector:
    app: {{ .Values.projectName | quote }}
    pod: workspace
    env: {{ .Values.labels.env | quote }}
  type: NodePort
  sessionAffinity: ClientIP
  ports: 
    - name: ssh
      port: 2202
      targetPort: ssh
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.projectName | quote }}
  labels:
    app: {{ .Values.projectName | quote }}
    env: {{ .Values.labels.env | quote }}
spec:
  selector:
    app: {{ .Values.projectName | quote }}
    pod: mysql
  type: ClusterIP
  ports: 
    - name: mysql
      port: 3306
      targetPort: mysql