apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-pv" .Values.projectName }}
  namespace: {{ .Values.projectName | quote }}
  labels:
    app: {{ .Values.projectName | quote }}
    env: {{ .Values.labels.env | quote }}
spec:
  storageClassName: {{ .Values.projectName | quote }}
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity: 
    storage: {{ .Values.volume.storage | quote }}
  hostPath: 
    path: {{ .Values.volume.hostPath | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-pvc" .Values.projectName }}
  namespace: {{ .Values.projectName | quote }}
  labels:
    app: {{ .Values.projectName | quote }}
    env: {{ .Values.labels.env | quote }}
spec:
  storageClassName: {{ .Values.projectName | quote }}
  accessModes: 
    - ReadWriteOnce
  selector: 
    matchLabels:
      app: {{ .Values.projectName | quote }}
  resources: 
    requests:
      storage: {{ .Values.volume.storage | quote }}