apiVersion: v1
kind: ConfigMap
metadata:
  name: geozemservis-nginx
  namespace: geozemservis
  labels:
    app: geozemservis
    env: stage
data: 
  nginx-php-stream: |
    upstream php-upstream { 
        server 127.0.0.1:9000; 
    }
immutable: true