apiVersion: v1
kind: Namespace
metadata:
  name: geozemservis
  labels:
    app: geozemservis
    env: stage
---
apiVersion: v1
kind: LimitRange
metadata:
  name: geozemservis
  namespace: geozemservis
  labels:
    app: geozemservis
    env: stage
spec:
  limits:
    - min:
        cpu: 0.2
        memory: 100Mi
      max:
        cpu: 2
        memory: 1Gi
      default:
        cpu: 0.2
        memory: 256Mi
      type: Container